"""Abstract base interfaces and data structures for the AI Core LLM layer.

This module defines the provider-independent BaseLLM interface that all LLM
adapters must implement, ensuring substitutability and consistent usage across
different AI applications.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, AsyncIterator, Iterator, Optional

from ai_core.config.models import GenerationConfig, LLMProviderConfig


@dataclass
class UsageMetadata:
    """Token usage statistics for an LLM generation call.

    Attributes:
        prompt_tokens: Number of tokens in the input prompt.
        completion_tokens: Number of tokens generated by the model.
        total_tokens: Total token count (prompt + completion).
    """

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


@dataclass
class LLMResponse:
    """Standardized response container returned by an LLM adapter.

    Attributes:
        content: The generated text content from the model.
        model_name: Identifier of the model that generated the response.
        provider_name: Identifier of the provider (e.g., 'gemini').
        finish_reason: Reason generation stopped (e.g., 'STOP', 'MAX_TOKENS').
        usage: Token consumption statistics.
        raw_response: Provider-specific raw response object for advanced debugging.
    """

    content: str
    model_name: str
    provider_name: str
    finish_reason: Optional[str] = None
    usage: UsageMetadata = field(default_factory=UsageMetadata)
    raw_response: Optional[Any] = None


class BaseLLM(ABC):
    """Abstract base class for all LLM provider adapters.

    All LLM provider implementations (e.g., GeminiAdapter, OpenAIAdapter) must
    inherit from this interface and implement its abstract methods. This ensures
    that any application layer can interact with any LLM provider without
    knowing provider-specific SDK details.

    Attributes:
        config: The provider configuration instance.
    """

    def __init__(
        self,
        config: LLMProviderConfig,
        client: Optional[Any] = None,
        **kwargs: Any,
    ) -> None:
        """Initializes the LLM adapter with a provider configuration.

        Args:
            config: An LLMProviderConfig containing model names, timeouts, and keys.
            client: Optional injected SDK module or client instance for testing or DI.
            **kwargs: Additional keyword arguments for future extensibility.
        """
        self.config = config
        self.client = client

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Returns the unique identifier of the LLM provider."""
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Returns the name of the model being used."""
        pass

    @abstractmethod
    def generate_content(
        self,
        user_message: str,
        *,
        system_prompt: Optional[str] = None,
        generation_config: Optional[GenerationConfig] = None,
    ) -> LLMResponse:
        """Synchronously generates a response from the LLM.

        Args:
            user_message: The prompt or input text from the user/application.
            system_prompt: Optional high-level system instruction or persona.
            generation_config: Optional generation parameters (temperature, max_tokens, etc.)
                that override default provider configurations.

        Returns:
            A standardized LLMResponse object containing the text and metadata.

        Raises:
            LLMProviderError: If the upstream LLM API call fails.
            LLMTimeoutError: If the request exceeds configured timeout limits.
            LLMRateLimitError: If provider rate limits are exceeded.
        """
        pass

    @abstractmethod
    async def agenerate_content(
        self,
        user_message: str,
        *,
        system_prompt: Optional[str] = None,
        generation_config: Optional[GenerationConfig] = None,
    ) -> LLMResponse:
        """Asynchronously generates a response from the LLM.

        Args:
            user_message: The prompt or input text from the user/application.
            system_prompt: Optional high-level system instruction or persona.
            generation_config: Optional generation parameters overriding defaults.

        Returns:
            A standardized LLMResponse object containing the text and metadata.

        Raises:
            LLMProviderError: If the upstream LLM API call fails.
            LLMTimeoutError: If the request exceeds configured timeout limits.
            LLMRateLimitError: If provider rate limits are exceeded.
        """
        pass

    @abstractmethod
    def generate_stream(
        self,
        user_message: str,
        *,
        system_prompt: Optional[str] = None,
        generation_config: Optional[GenerationConfig] = None,
    ) -> Iterator[str]:
        """Synchronously yields response chunks as they are generated.

        Args:
            user_message: The prompt or input text from the user/application.
            system_prompt: Optional high-level system instruction or persona.
            generation_config: Optional generation parameters overriding defaults.

        Yields:
            String chunks of the generated response.

        Raises:
            LLMProviderError: If the upstream streaming API call fails.
        """
        pass

    @abstractmethod
    async def agenerate_stream(
        self,
        user_message: str,
        *,
        system_prompt: Optional[str] = None,
        generation_config: Optional[GenerationConfig] = None,
    ) -> AsyncIterator[str]:
        """Asynchronously yields response chunks as they are generated.

        Args:
            user_message: The prompt or input text from the user/application.
            system_prompt: Optional high-level system instruction or persona.
            generation_config: Optional generation parameters overriding defaults.

        Yields:
            String chunks of the generated response.

        Raises:
            LLMProviderError: If the upstream streaming API call fails.
        """
        pass
