"""Conversation Engine orchestrating message flow and session lifecycle.

This module implements the ConversationEngine, which coordinates conversation
state and message history while delegating all text generation to an injected
BaseLLM instance. It never builds prompts or interacts with provider SDKs directly.
"""

from typing import Any, AsyncIterator, Iterator, Optional

from ai_core.config.models import GenerationConfig
from ai_core.conversation.exceptions import ConversationException
from ai_core.conversation.models import ConversationState, Message
from ai_core.conversation.state import ConversationStateManager
from ai_core.llm.base import BaseLLM


class ConversationEngine:
    """Orchestrates message turns, history tracking, and conversation lifecycle.

    The ConversationEngine relies on dependency injection for its LLM adapter
    (`BaseLLM`) and state manager (`ConversationStateManager`). It does not
    construct or render prompt templates.

    Attributes:
        llm: The injected domain-agnostic LLM adapter.
        state_manager: The session state and lifecycle controller.
    """

    def __init__(
        self,
        llm: BaseLLM,
        state_manager: Optional[ConversationStateManager] = None,
    ) -> None:
        """Initializes the ConversationEngine.

        Args:
            llm: An instance implementing BaseLLM.
            state_manager: Optional state manager. If None, a new manager is created.

        Raises:
            ConversationException: If llm does not implement BaseLLM.
        """
        if not isinstance(llm, BaseLLM):
            raise ConversationException(
                f"ConversationEngine requires an instance of BaseLLM, got {type(llm).__name__}."
            )
        self.llm = llm
        self.state_manager = state_manager or ConversationStateManager()

    @property
    def conversation_id(self) -> str:
        """Returns the unique session identifier."""
        return self.state_manager.conversation_id

    @property
    def state(self) -> ConversationState:
        """Returns the current conversation lifecycle state."""
        return self.state_manager.state

    def start(self) -> None:
        """Transitions the conversation session to ACTIVE state."""
        self.state_manager.start()

    def pause(self) -> None:
        """Pauses an active conversation session."""
        self.state_manager.pause()

    def resume(self) -> None:
        """Resumes a paused conversation session."""
        self.state_manager.resume()

    def end(self) -> None:
        """Terminates the conversation session."""
        self.state_manager.end()

    def get_history(self) -> list[Message]:
        """Returns a copy of the conversation message history."""
        return self.state_manager.get_history()

    def _ensure_active(self) -> None:
        """Automatically starts the conversation if INITIALIZED or PAUSED."""
        if self.state in (ConversationState.INITIALIZED, ConversationState.PAUSED):
            self.start()

    def process_message(
        self,
        user_message: str,
        *,
        system_prompt: Optional[str] = None,
        generation_config: Optional[GenerationConfig] = None,
    ) -> Message:
        """Synchronously processes a user message turn through the LLM.

        Args:
            user_message: The text message from the user.
            system_prompt: Optional pre-rendered system instruction string.
            generation_config: Optional LLM generation parameter overrides.

        Returns:
            The assistant Message instance generated by the model.

        Raises:
            ConversationLifecycleError: If the conversation is ended or in error.
            LLMException: If LLM generation fails.
        """
        self._ensure_active()

        self.state_manager.add_user_message(user_message)

        response = self.llm.generate_content(
            user_message,
            system_prompt=system_prompt,
            generation_config=generation_config,
        )

        metadata: dict[str, Any] = {
            "model_name": response.model_name,
            "provider_name": response.provider_name,
            "finish_reason": response.finish_reason,
            "usage": {
                "prompt_tokens": response.usage.prompt_tokens,
                "completion_tokens": response.usage.completion_tokens,
                "total_tokens": response.usage.total_tokens,
            },
        }

        return self.state_manager.add_assistant_message(response.content, metadata=metadata)

    async def aprocess_message(
        self,
        user_message: str,
        *,
        system_prompt: Optional[str] = None,
        generation_config: Optional[GenerationConfig] = None,
    ) -> Message:
        """Asynchronously processes a user message turn through the LLM.

        Args:
            user_message: The text message from the user.
            system_prompt: Optional pre-rendered system instruction string.
            generation_config: Optional LLM generation parameter overrides.

        Returns:
            The assistant Message instance generated by the model.

        Raises:
            ConversationLifecycleError: If the conversation is ended or in error.
            LLMException: If LLM generation fails.
        """
        self._ensure_active()

        self.state_manager.add_user_message(user_message)

        response = await self.llm.agenerate_content(
            user_message,
            system_prompt=system_prompt,
            generation_config=generation_config,
        )

        metadata: dict[str, Any] = {
            "model_name": response.model_name,
            "provider_name": response.provider_name,
            "finish_reason": response.finish_reason,
            "usage": {
                "prompt_tokens": response.usage.prompt_tokens,
                "completion_tokens": response.usage.completion_tokens,
                "total_tokens": response.usage.total_tokens,
            },
        }

        return self.state_manager.add_assistant_message(response.content, metadata=metadata)

    def stream_message(
        self,
        user_message: str,
        *,
        system_prompt: Optional[str] = None,
        generation_config: Optional[GenerationConfig] = None,
    ) -> Iterator[str]:
        """Synchronously streams an assistant response turn.

        Args:
            user_message: The text message from the user.
            system_prompt: Optional pre-rendered system instruction string.
            generation_config: Optional LLM generation parameter overrides.

        Yields:
            String chunks of the generated response.

        Raises:
            ConversationLifecycleError: If the conversation is ended or in error.
            LLMException: If LLM streaming fails.
        """
        self._ensure_active()

        self.state_manager.add_user_message(user_message)

        collected_chunks: list[str] = []
        for chunk in self.llm.generate_stream(
            user_message,
            system_prompt=system_prompt,
            generation_config=generation_config,
        ):
            collected_chunks.append(chunk)
            yield chunk

        full_content = "".join(collected_chunks)
        self.state_manager.add_assistant_message(full_content)

    async def astream_message(
        self,
        user_message: str,
        *,
        system_prompt: Optional[str] = None,
        generation_config: Optional[GenerationConfig] = None,
    ) -> AsyncIterator[str]:
        """Asynchronously streams an assistant response turn.

        Args:
            user_message: The text message from the user.
            system_prompt: Optional pre-rendered system instruction string.
            generation_config: Optional LLM generation parameter overrides.

        Yields:
            String chunks of the generated response.

        Raises:
            ConversationLifecycleError: If the conversation is ended or in error.
            LLMException: If LLM streaming fails.
        """
        self._ensure_active()

        self.state_manager.add_user_message(user_message)

        collected_chunks: list[str] = []
        async for chunk in self.llm.agenerate_stream(
            user_message,
            system_prompt=system_prompt,
            generation_config=generation_config,
        ):
            collected_chunks.append(chunk)
            yield chunk

        full_content = "".join(collected_chunks)
        self.state_manager.add_assistant_message(full_content)
